project:
  type: website
  output-dir: docs

website:
  title: "DATASCI 385"
  page-navigation: true
  back-to-top-navigation: true
  reader-mode: true
  repo-url: https://github.com/danilofreire/datasci385
  repo-actions: [issue, source]
  repo-branch: gh-pages
  navbar:
    pinned: true
    tools:
      - icon: github
        href: https://github.com/danilofreire/datasci385
    left:
      - href: syllabus.qmd
        text: Syllabus
      - href: lectures.qmd
        text: Lectures
      - href: assignments.qmd
        text: Assignments
      - href: guides.qmd
        text: Guides
      - href: LICENSE.html
        text: " "
  page-footer: 
    left: "The content of this site is licensed under the [MIT License](LICENSE.qmd)." 
    right: 
      - icon: github
        href: https://github.com/danilofreire/datasci385

format:
  html:
    theme: 
      light: lumen
      dark: solar
    toc: true

